### ISSUE TITLE
[Events] Generated empty event name when emitted one contain numbers

### ISSUE THREAD

**Issue by h0s** [ady642/vest#1]
## Context

When generating test for an events that contain numbers in title , the tests are generated with empty name of the event.
## Process

1. Emit an event with name "to-do-1"
2. Generate unit test using Vest
3. The generated test contains `expect(wrapper.emitted('')).toHaveLength(1)` instead of `expect(wrapper.emitted('to-do-1')).toHaveLength(1)`

## Expected result

`expect(wrapper.emitted('to-do-1')).toHaveLength(1)`

## Current result

`expect(wrapper.emitted('')).toHaveLength(1)`

## Possible Fix
Modify the regex to match both numbers & characters in https://github.com/ady642/vest/blob/063297a787acdfcde2ffb8d17493d32942de3708/src/templates/EventFactory/EventFactory.ts#L72

**Comment by ady642** [comment]
resolve in https://github.com/ady642/vest/commit/ff66f6dcf6f08578177cf96e54b1a7ef4d8c5122
